### ISSUE TITLE
Suggestion : Remove the difference in editors about right-click

### ISSUE THREAD

**Issue by GreenRoadblock** [GM82Project/gm82room#10]
in built-in editor，the right-click is menu, but in this external editor is delete. 
i guess it's a weird difference. may we can have a option to switch the action in preferences?

**Comment by omicronrex** [comment]
i'm not sure it would make sense, since there is no right click menu in the new room editor. everything is done via the inspector panel.

**Comment by GreenRoadblock** [comment]
i dont know how to describe it in english, i just have a bit of uncomfortable to using right-click to delete

**Comment by omicronrex** [comment]
Sorry, i can't change that because it would conflict with the stacked instance menu and selection moving controls. It would also impact muscle memory for people since the controls have been like that since the editor was first released 3 years ago.

**Comment by GreenRoadblock** [comment]
wait, i just want a new switch in the preferences to swap RMB and CTRL+RMB, so that we can change the action based on own habit :^(

**Comment by omicronrex** [comment]
I'll see what i can do.

**Comment by GreenRoadblock** [comment]
i dont know why i asked this after i tried, probably just tired. my bad, sorry :P

**Comment by omicronrex** [comment]
Are you sure you don't want the option? I can still add it. It makes sense if you're coming from the 8.1 editor.

**Comment by GreenRoadblock** [comment]
if this doesnt make needless trouble?

**Comment by omicronrex** [comment]
Naw, it's a perfectly valid complaint. I'll add a checkbox for it. It'll probably even help me too since i frequently use right click as a 'deselect' action.

**Comment by omicronrex** [comment]
added in 92d6e3dfe5cade8d594f57ec51ca63c29575de21.
