### ISSUE TITLE
Suggestion : More flexible jtool importing support

### ISSUE THREAD

**Issue by Cheri2** [GM82Project/gm82room#9]
Currently, it's not possible to add more than 27 default objects to jtool import list, and trying so would result in error.
I would like to use custom jtool mod, that includes more gimmicks for making my fangame. However, I got to import custom objects manually, since I can't assign unused numbers (in .jmap files) to more objects.
It would be good idea to allow adding more jtool objects by user, for advanced users who want to use ctool, topi's jtool mod, etc.

**Comment by omicronrex** [comment]
Doesn't look too complicated to add, i'll look into it at some point soon.

**Comment by omicronrex** [comment]
implemented in e6037828473520477e523776847fb63c525e6a00
